### ISSUE TITLE
 Write a Code [ Python, CPP, C, JAVA, JS ] to solve the Leetcode Problem 

### ISSUE THREAD

**Issue by saptarshisarkar20** [saptarshisarkar20/Novice-Coding#18]
# Reverse Bits
## Statement
Reverse bits of a given 32 bits unsigned integer.

Note:

* Note that in some languages, such as Java, there is no unsigned integer type. In this case, both input and output will be given as a signed integer type. They should not affect your implementation, as the integer's internal binary representation is the same, whether it is signed or unsigned.
* In Java, the compiler represents the signed integers using 2's complement notation. Therefore, in Example 2 above, the input represents the signed integer -3 and the output represents the signed integer -1073741825.

### Example 1:
```
Input: n = 00000010100101000001111010011100
Output:    964176192 (00111001011110000010100101000000)
```
Explanation: The input binary string 00000010100101000001111010011100 represents the unsigned integer 43261596, so return 964176192 which its binary representation is 00111001011110000010100101000000.

### Example 2:
```
Input: n = 11111111111111111111111111111101
Output:   3221225471 (10111111111111111111111111111111)
```
Explanation: The input binary string 11111111111111111111111111111101 represents the unsigned integer 4294967293, so return 3221225471 which its binary representation is 10111111111111111111111111111111.

### Constraints:

The input must be a binary string of length 32

 

#### Follow up: If this function is called many times, how would you optimize it?

# **RULES :** 

* Star this repository.
* Fork this repository
* No need to wait for getting assigned, you can go ahead attempt the issues and raise a PR.
* We will review any comments or PRs at 5 PM & 10 PM on 1st Oct, will give feedback if needed.

## How to name your file?

    

1. Go to folder : "/LeetCode/TwoSum/"
2. Take today's date, i.e. 1stOct
3. Take your GitHUB username id like "hrithik339", "hacker-boy", etc or anything which you have.
4. File extension = say ".py" .

* **Combine all 3 to get your file name : Date + "_" + Username + File Extension, ex. "1stOct_hrithik339.py". Create this file in above mentioned folder only,**

This will ensure no file will be conflict and any number of contributors can work on the same issue.
If you have any query ask in comments below, kindly follow this pattern strictly.

**Comment by sushant-iit** [comment]
Working

**Comment by sushant-iit** [comment]
#21 I have created a solution for that. Please merge it.

**Comment by ranjit7858** [comment]
#18 I have created solution for the issue. Please kindly merge it

**Comment by Prakhar-Dixit** [comment]
Can we still contribute to this repository or it was only to be get contributed on 1st OCT ?

**Comment by ayush523** [comment]
Hi.I have solved this in python.

**Comment by saptarshisarkar20** [comment]
> Can we still contribute to this repository or it was only to be get contributed on 1st OCT ?

You can

**Comment by harshpatel2212** [comment]
@saptarshisarkar20 I would like to work on this issue.
