### ISSUE TITLE
 Write a code to Solve the Hackerrank Simple Array Sum Problem [C, C++, Python, Java, JS, Php] 

### ISSUE THREAD

**Issue by saptarshisarkar20** [saptarshisarkar20/Novice-Coding#7]
# Simple Array Sum
## Statement

Given an array of integers, find the sum of its elements.

For example, if the array
arr = [1,2,3] so return 6

Function Description

Complete the simpleArraySum function in the editor below. It must return the sum of the array elements as an integer.
simpleArraySum has the following parameter(s):
ar: an array of integers

## Input Format

The first line contains an integer n, denoting the size of the array.
The second line contains space-separated integers representing the array's elements.

## Constraints

0 <= n,arr[i] <= 1000

## Output Format

Print the sum of the array's elements as a single integer.

### Sample Input
```
6
1 2 3 4 10 11
```
### Sample Output
```
31
```
### Explanation

We print the sum of the array's elements: 1+2+3+4+10+11 = 31

# **Rules**

* Star this repository.
* Fork this repository
* No need to wait for getting assigned, you can go ahead attempt the issues and raise a PR.
* We will review any comments or PRs at 5 PM & 10 PM on 1st Oct, will give feedback if needed.

## How to name your file?

    

1. Go to folder : "/HackerRank/Simple Array Sum/"
2. Take today's date, i.e. 1stOct
3. Take your GitHUB username id like "hrithik339", "hacker-boy", etc or anything which you have.
4. File extension = say ".py" .

* **Combine all 3 to get your file name : Date + "_" + Username + File Extension, ex. "1stOct_hrithik339.py". Create this file in above mentioned folder only,**

This will ensure no file will be conflict and any number of contributors can work on the same issue.
If you have any query ask in comments below, kindly follow this pattern strictly.

**Comment by arihantthriwe** [comment]
Please assign me this :)

**Comment by saptarshisarkar20** [comment]
> Please assign me this :)
> 

No need to wait for getting assigned, you can go ahead attempt the issues and raise a PR.

**Comment by arihantthriwe** [comment]
OK thanks :)

**Comment by SanthoshS20** [comment]
@saptarshisarkar20 is this project is participating in the hacktoberfest 2021?

**Comment by arihantthriwe** [comment]
@saptarshisarkar20 this project is not participating in Hacktoberfest

**Comment by arihantthriwe** [comment]
Please check @saptarshisarkar20

**Comment by saptarshisarkar20** [comment]
I have added it into the Project

**Comment by arihantthriwe** [comment]
Please Check:)
<img width="1680" alt="Screenshot 2021-10-02 at 7 20 29 PM" src="https://user-images.githubusercontent.com/85555201/135719273-54d7dd26-e09b-40da-86c8-eb197dd723ba.png">

@saptarshisarkar20

**Comment by RaghavvGupta** [comment]
Is this issue still available, I would like to contribute in C++

**Comment by cereal-hecker** [comment]
hey, pls assign this to me

**Comment by saptarshisarkar20** [comment]
> hey, pls assign this to me, i'd like to contribute in cpp
> 

Please find the issue in my other repository Hacktoberfest2022
